[project]
name = "appa-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib==3.10.1",
    "numpy==2.2.4",
    "pandas>=2.3.1",
    "tiktoken==0.9.0",
    "torch>=2.8.0",
    "tqdm==4.66.5",
]
